version: "3"

services:
  minio:
    image: minio/minio:latest
    env_file:
      - .env
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_storage:/data
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_storage: {}
